"""fourth migrations

Revision ID: 7ba43bde60a6
Revises: a415560d9964
Create Date: 2018-04-18 16:45:56.348000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba43bde60a6'
down_revision = 'a415560d9964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'time')
    # ### end Alembic commands ###
