"""update_time

Revision ID: 861e892b45e2
Revises: c8063789c9cd
Create Date: 2018-06-07 21:18:00.695000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861e892b45e2'
down_revision = 'c8063789c9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'update_time')
    # ### end Alembic commands ###
